[build]
  publish = "."
  command = "echo 'Zeeky AI deployment ready'"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/launch"
  to = "/launch_announcement.html"
  status = 200

[[redirects]]
  from = "/beta"
  to = "/beta_program.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
