# Netlify configuration for Zeeky AI
[build]
  publish = "frontend"
  command = "echo 'Static site - no build needed'"

  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Production context
[context.production]
  publish = "frontend"
  command = "echo 'Static site - no build needed'"

  [context.production.environment]
    NODE_ENV = "production"
    ZEEKY_ENV = "production"

# Deploy preview context
[context.deploy-preview]
  publish = "frontend"
  command = "echo 'Static site - no build needed'"

  [context.deploy-preview.environment]
    NODE_ENV = "staging"
    ZEEKY_ENV = "staging"

# Main redirect - serve index.html for root
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# SPA routing - all routes serve index.html
[[redirects]]
  from = "/chat"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/avatar"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/features"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200

# API proxy (update with your actual backend URL when deployed)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.herokuapp.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Health check endpoint
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Handle all other routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enhanced Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' wss: ws: https:; media-src 'self'; object-src 'none'"

# Cache static assets
[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

# Functions (for serverless backend)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Form handling
[forms]
  settings = { spam_protection = true }

# Dev server settings
[dev]
  command = "npm run serve"
  port = 8000
  publish = "frontend"
  autoLaunch = true

# Build processing
[build.processing]
  skip_processing = false

  [build.processing.css]
    bundle = true
    minify = true

  [build.processing.js]
    bundle = true
    minify = true

  [build.processing.html]
    pretty_urls = true

  [build.processing.images]
    compress = true

# Environment variables (set in Netlify dashboard)
# OPENAI_API_KEY = "your-openai-key"
# GEMINI_API_KEY = "your-gemini-key"
# ZEEKY_VERSION = "1.0.0"
