# Netlify configuration for Zeeky AI
[build]
  publish = "frontend"
  command = ""

# Redirect rules for clean URLs
[[redirects]]
  from = "/"
  to = "/master-dashboard.html"
  status = 200

[[redirects]]
  from = "/chat"
  to = "/chat.html"
  status = 200

[[redirects]]
  from = "/avatar"
  to = "/zeeky_avatar_interface.html"
  status = 200

[[redirects]]
  from = "/onboarding"
  to = "/onboarding-flow.html"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/beta-analytics-dashboard.html"
  status = 200

[[redirects]]
  from = "/launch"
  to = "/public-launch-center.html"
  status = 200

[[redirects]]
  from = "/growth"
  to = "/growth-optimization-center.html"
  status = 200

[[redirects]]
  from = "/beta"
  to = "/beta-launch-dashboard.html"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/master-dashboard.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (set in Netlify dashboard)
# OPENAI_API_KEY = "your-openai-key"
# GEMINI_API_KEY = "your-gemini-key"
