[build]
  # Build command - since this is a static site, we just need to ensure files are ready
  command = "npm run build"

  # Publish directory - the root directory contains our static files
  publish = "."

  # Base directory - use the repository root
  base = "."

  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "8"

# Redirect rules for SPA behavior
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https: wss: ws:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Form handling
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Edge Functions Configuration
[[edge_functions]]
  function = "personalization"
  path = "/*"

[[edge_functions]]
  function = "localization"
  path = "/*"

[[edge_functions]]
  function = "performance"
  path = "/*"

[[edge_functions]]
  function = "api-aggregator"
  path = "/edge-api/*"

[[edge_functions]]
  function = "auth"
  path = "/auth/*"

# Environment Variables for Edge Functions
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  ZEEKY_EDGE_FUNCTIONS = "true"
