workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.joachimaross.zeekyai"
        GOOGLE_PLAY_TRACK: internal
      node: 18.17.0
      npm: 9.6.7
      ndk: r25b
      java: 11
    scripts:
      - name: Install npm dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ZeekyAIMobile/ios && pod install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/ZeekyAIMobile/android/local.properties"
      - name: Build Android release
        script: |
          cd ZeekyAIMobile
          # Set the build number to timestamp
          export NEW_BUILD_NUMBER=$(($(date +'%s') / 60))
          npx react-native run-android --variant=release
    artifacts:
      - ZeekyAIMobile/android/app/build/outputs/**/*.apk
      - ZeekyAIMobile/android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.joachimaross.zeekyai
      vars:
        APP_ID: 1234567890 # <-- Put your app id number here
        BUNDLE_ID: "com.joachimaross.zeekyai"
        XCODE_WORKSPACE: "ZeekyAIMobile/ios/ZeekyAIMobile.xcworkspace"
        XCODE_SCHEME: "ZeekyAIMobile"
      node: 18.17.0
      npm: 9.6.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ZeekyAIMobile/ios && pod install
      - name: Increment build number
        script: |
          cd ZeekyAIMobile/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          cd ZeekyAIMobile/ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - ZeekyAIMobile/ios/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ZeekyAIMobile/ios/flutter_drive.log
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        EAS_PROJECT_ID: zeeky-ai-mobile-project
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g @expo/eas-cli
          npm install -g expo-cli
      - name: Expo login
        script: |
          eas login --non-interactive
      - name: Build Android with EAS
        script: |
          cd ZeekyAIMobile
          eas build --platform android --non-interactive --no-wait
    artifacts:
      - ZeekyAIMobile/*.apk
      - ZeekyAIMobile/*.aab
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: true
          failure: false

  expo-ios:
    name: Expo iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - expo_credentials
        - app_store_credentials
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        EAS_PROJECT_ID: zeeky-ai-mobile-project
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g @expo/eas-cli
          npm install -g expo-cli
      - name: Expo login
        script: |
          eas login --non-interactive
      - name: Build iOS with EAS
        script: |
          cd ZeekyAIMobile
          eas build --platform ios --non-interactive --no-wait
    artifacts:
      - ZeekyAIMobile/*.ipa
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: true
          failure: false

  expo-preview:
    name: Expo Preview Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    environment:
      groups:
        - expo_credentials
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        EAS_PROJECT_ID: zeeky-ai-mobile-project
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g @expo/eas-cli
          npm install -g expo-cli
      - name: Expo login
        script: |
          eas login --non-interactive
      - name: Build preview
        script: |
          cd ZeekyAIMobile
          eas build --platform all --profile preview --non-interactive --no-wait
    artifacts:
      - ZeekyAIMobile/*.apk
      - ZeekyAIMobile/*.ipa
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: true
          failure: false

  tests:
    name: Unit Tests
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 18.17.0
      npm: 9.6.7
    scripts:
      - name: Install dependencies
        script: |
          cd ZeekyAIMobile
          npm install
      - name: Run tests
        script: |
          cd ZeekyAIMobile
          npm test -- --coverage --watchAll=false
      - name: Run linting
        script: |
          cd ZeekyAIMobile
          npm run lint
    artifacts:
      - ZeekyAIMobile/coverage/**/*
    publishing:
      email:
        recipients:
          - zeekyai@hotmail.com
        notify:
          success: false
          failure: true
